---
applications:
- name: project-monitor-production
  memory: 1024M
  instances: 3
  host: project-monitor-production
  path: ../../
  command: bundle exec rake db:migrate && bundle exec unicorn -p $PORT -c ./config/unicorn.rb
  services:
  - db-production
  - logentries-production-web
- name: project-monitor-production-worker
  memory: 512M
  instances: 1
  path: ../../
  command: bundle exec rake jobs:work
  no-route: true
  services:
  - db-production
  - logentries-production-worker
- name: project-monitor-production-clockwork
  memory: 512M
  instances: 1
  path: ../../
  command: bundle exec clockwork ./clockwork.rb
  no-route: true
  services:
  - db-production
  - logentries-production-clockwork
- name: project-monitor-production-poller
  memory: 1024M
  instances: 1
  path: ../../
  command: bundle exec rake projectmonitor:poller
  no-route: true
  services:
  - db-production
  - logentries-production-poller
