---
applications:
- name: project-monitor-staging
  memory: 512M
  instances: 1
  host: project-monitor-staging
  path: ../../
  command: bundle exec rake db:migrate && bundle exec unicorn -p $PORT -c ./config/unicorn.rb
  services:
  - db-staging
  - logentries-staging-web
- name: project-monitor-staging-worker
  memory: 512M
  instances: 1
  path: ../../
  command: bundle exec rake jobs:work
  no-route: true
  services:
  - db-staging
  - logentries-staging-worker
- name: project-monitor-staging-clockwork
  memory: 512M
  instances: 1
  path: ../../
  command: bundle exec clockwork ./clockwork.rb
  no-route: true
  services:
  - db-staging
  - logentries-staging-clockwork
- name: project-monitor-staging-poller
  memory: 1024M
  instances: 1
  path: ../../
  command: bundle exec rake projectmonitor:poller
  no-route: true
  services:
  - db-staging
  - logentries-staging-poller
