---
defaults:
  install_options: --no-ri --no-rdoc
gems:
- name: rails
  version: 2.3.5
- name: rack
  version: 1.0.1
- name: rake
  version: 0.8.7
- name: gem_plugin
  version: 0.2.3
- name: mime-types
  version: 1.15
- name: mongrel
  version: >= 1.1.5
- name: mongrel_cluster
  version: 1.0.5
- name: libxml-ruby
  version: 1.1.2
- name: nokogiri
  version: 1.4.1
- name: httpauth
  version: 0.1
- name: hpricot
- name: rspec-rails
  version: >= 1.1.11
- name: jviney-acts_as_taggable_on_steroids
  version: 1.1
  install_options: --source http://gems.github.com
- name: acts_as_taggable
  version: ~> 2.0.2
- name: jasmine
  version: 0.10.3.1
