#
# Format:
#
# <stage name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   tag: <git tag pattern, optional>
#   repo: <git repository, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
production:
  app: projectmonitor-production
  stack: cedar
  tag: production/*
  config:
    BUNDLE_WITHOUT: "development:test"

staging:
  app: projectmonitor-staging
  stack: cedar
  config:
    BUNDLE_WITHOUT: "development:test"
